### ISSUE TITLE
Баннерная реклама на сайте

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#10]

**Comment by SvetlanaAlabieva** [comment]
Хотели уточнить вот какой вопрос. Мы на сайте планируем иметь места под баннерную рекламу, а также место под рекламу и пиар закупок организаторов, т.к. это будет являться доп. доходом для нас. Место будет предусмотрено под рекламу?

**Comment by tibrus** [comment]
Конечно. Сайт построен полностью на новых технологиях, и не привязан по секциям или блокам. 
Поэтому любой блок динамично встраивается.

**Comment by SvetlanaAlabieva** [comment]
Здорово!!!
