### ISSUE TITLE
Нюансы в закупках

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#12]
Можно попросить сделать фото на этой странице в закупке http://sp.exoohub.com/sp/purchases/view#-поменьше, а при нажатии на саму фотографию она будет раскрываться и увеличиваться. И хотелось бы где идет ник орга (на этой же странице)-сделать отзывы о работе организатора а где название закупки-отзывы о самой закупке. Иногда решающим фактором при выборе закупки играет роль сам организатор и качество товара. особенно новичкам это помогает сделать выбор.

**Comment by SvetlanaAlabieva** [comment]
Доставка не всегда бывает известна сразу. http://sp.exoohub.com/sp/purchases/view Очень часто бывает так что точную стоимость доставки можно узнать лишь после оплаты и отправки товара. И в этом отчете Вы просили напомнить чтоб графа была пустая в том случае, если по первой ссылке сумма доставки не заполнена. http://sp.exoohub.com/sp/organizer/orders

**Comment by tibrus** [comment]
> отзывы о работе организатора
> отзывы о самой закупке
Ок, просто не успели еще добавить

>Доставка не всегда бывает известна сразу
Ок. Учтем.

**Comment by OksanaN** [comment]
А я думаю, может, не делать ОТЗЫВ ОБ ОРГАНИЗАТОРЕ? 
Как Игорб говорил при встрече, что тогда получится базар и свалка на сайте, что конкуренты будут писать плохие отзывы об организаторе.
Игорь, поясните еще раз,  как на ваш взгляд лучше - делать отзывы об организаторе или нет?

**Comment by tibrus** [comment]
Лучший отзыв об организаторе это его проделанная работа.
Если после первой закупки он не забанен, значит неплохо поработал)))
А если за плечами более 4-5 то можно доверять. И т.д.

Допустим обманутый заказчик напишет отрицательный отзыв, и что? А так ли оно?

Лучше создать специальные статусы для организатора и присваивать их по мере работы.
А вместо жалоб в отзывах или т.п. ""хвасты" (смеялся долго), лучше создать систему расследования случаев обмана и т.п. Где заказчик пишет администраторам сайта, для просьбы проведения расследования обмана или недобросовестной работы организатора.

**Comment by OksanaN** [comment]
"Хвасат" 9ударение на первый слог, от слова "хвастать" - это общепринятый в СП термин ,когда участники выкладывают фото товара после приобретения, так сказать, "в живую".
А на счет системы расследования, как она будет выглядеть? Она будет доступна для всех польхователей сайта или только для участников конфликта?

**Comment by OksanaN** [comment]
И что за статусы для организатора? Кто их будет присваивать?

**Comment by tibrus** [comment]
Оксана, Вы поймите меня правильно, мы разработчики программного обеспечения, мы не занимаемся организацией бизнеса. Можем только советовать.
Вы даете задание, мы его воплощаем в виде кода.

**Comment by OksanaN** [comment]
Ну присваивать статусы будем мы, администраторы или каким-то образом участники будут в это вносить свою лепту?

**Comment by SvetlanaAlabieva** [comment]
Если участники будут вносить свою лепту это получится по сути тоже самое что и плохие отзывы. Будут писать все что им в голову взбредет. Я думаю нужно сделать статусы и присваиваться они будут автоматически (если это возможно будет сделать). Т.е. к примеру если ОРГ. провел уже более 10 закупок на сайте ему будет присваиваться статус опытный организатор ну или что-то в том роде.....надо подумать.

**Comment by SvetlanaAlabieva** [comment]
либо администраторы будут присваивать статусы

**Comment by SvetlanaAlabieva** [comment]
На счет отзывов об организаторе я считаю что все таки они нужны, но возможно надо будет сделать так, что прежде чем пользователь захочет оставить плохой отзыв,  сначала он будет отправляться автоматически нам на проверку или как Вы написали на расследование и если пользователь докажет свою правоту, тогда мы его будем пропускать.

**Comment by SvetlanaAlabieva** [comment]
Если возможно будет сделать так технически, то можно сделать 5 бальную шкалу оценки работы организатора и если пользователь ставит 4 либо 5 оценку то такой отзыв считается положительным и он автоматически пропускается программой, если же пользователь ставит оценку ниже, то в этом случае (скорее всего это будет плохой отзыв) программа будет отправлять нам для уточнения всех деталей и рассмотрения данного отрицательного отзыва.

**Comment by tibrus** [comment]
> ставит 4 либо 5 оценку то такой отзыв считается положительным 

Не факт. Орг регистрирует на сайте 10 аккаунтов и плюсует все свои закупки на постоянной основе. Такая практика будет у половины оргов.

**Comment by OksanaN** [comment]
Я бы не дадумалась регистрироваться 10 раз и ставить себе оценки)))
Может, ставить оценки может только тот, кто участвовал у этого орга в закупке?

**Comment by SvetlanaAlabieva** [comment]
Да, согласна с Оксаной, что отзыв имеет право поставить только тот пользователь кто непосредственно принимал участие в определенной закупке. Причем это можно будет сделать сразу в корзине заказанных товаров, когда пользователь уже получил свой товар он у него высвечивается в полученных товарах и там же сделать кнопку написать отзыв
