### ISSUE TITLE
Типы дополнительных полей у товара

### ISSUE THREAD

**Issue by tibrus** [exoohub/sp#13]
Необходимо предусмотреть все типы дополнительных полей у товара.

Свойство товара | Пример | Тип
----------- | ------------- | ------------
Размер | 46,47,48,49,50... | массив
Длина | 30 | текст
Ширина | 30 | текст
Высота | 30 | текст
Объем | 30 | текст
Цвет | белый | текст
Состав | 100% хлопок | текст
Вес | 10кг. | текст
Производитель | Китай | текст

Вспоминаем, ищем, предлагаем)))

**Comment by mufasaAG** [comment]
А нечего больше не надо. Цвет да, Тип массив мне не понятен и не встречал, слишком много инфы загружать не надо, только конкретика

**Comment by mufasaAG** [comment]
в принципе ничего больше и не надо, не понятен тип - массив, а так все остальное норм и лишнего ничего нет

Может быть добавить зум на фотку товара? Но может быть так, что загрузят картинки по качеству гамно, что аж страшно увеличивать)

**Comment by OksanaN** [comment]
1) Состав товара тоже сюда, в поля относим или где-то в другом месте будут? (100% хлопок, вискоза и т.д)
2) у некоторых поставщиков на некоторые товары указывается вес.
3) производитель

**Comment by OksanaN** [comment]
И еще, я почему-то не вижу тем, созданных Светланой.
У меня всего 5 открытых тем.
Насколько я понимаю, их больше в данный момент.

**Comment by tibrus** [comment]
> Состав, вес, производитель

Добавил в таблицу

> не вижу тем, созданных Светланой

Связано с тем, что Вы выбрали фильтр. Если нажать например на желтую метку "Обсуждение". то будут показаны все темы с этой меткой.

Сброс фильтра находится в верхней части таблицы с вопросами.

![image](https://cloud.githubusercontent.com/assets/6314709/6663409/7354d7d6-cbd7-11e4-8a71-f2c4fafa500b.png)

**Comment by OksanaN** [comment]
1)Объем (это у женского нижнего белья)
2) Например. у предметов интерьера - картины, фоторамки, да и у других товаров - ширина. высота, длинна, глубина...

**Comment by OksanaN** [comment]
А у обуви также пишут сколько см стелька.
То есть 38 размер - 24,5см.
Потому что у разных производителей может быть разная размерная сетка. И участники закупок пои заказах обуви в первую очередь спрашивают сколько см по стельке.

**Comment by tibrus** [comment]
> А у обуви также пишут сколько см стелька.
То есть 38 размер - 24,5см.
Потому что у разных производителей может быть разная размерная сетка. И участники  закупок пои заказах обуви в первую очередь спрашивают сколько см по стельке.

Это скорее в описании самой закупки нужно описывать, иначе мы усложним свойства товара, и они будут с подсвойствами...

**Comment by OksanaN** [comment]
Добрый день!
Подготавляваю свойства товаров.
Хотела уточнить, всё ли верно делаю.

ОДЕЖДА
1.Производитель/ТМ (торговая марка):  Россия/Open Fashion
2.Состав:  90% хлопок, 10% спандекс

для верхней одежды состав более расширенный
внутр.материал-полиэстер
внешний материал-плащевка
наполнитель – пух
мех – натуральный енот
 3. Размер: 44
4. Рост: 160
5.Параметры:
ОГ (объем груди) 90
ОТ (объем талии) 60
ОБ (объем бедер) 90
6.Цвет: белый
7.Вес: 100гр

**Comment by OksanaN** [comment]
ОБУВЬ
1.Производитель/Торговая марка
2.Внутренний материал
3.Наружный материал
4.Размер
5.Стелька (см)
6.Цвет
7.Вес

**Comment by OksanaN** [comment]
Белье и купальники
1) Производитель/ТМ
2)Состав
3)Размер (44.46...)
4)Параметры:
-ОГ (объем груди)
-ОТ (объем талии)
-ОБ (объем бедер)
5)Объем (70А. 75В, 80С....)
6)Цвет

**Comment by OksanaN** [comment]
Чулочно-носочные изделия 
1) Производитель/ТМ
2)Состав
3)Размер
4)Плотность (20ден, 40ден...)
5)Цвет

**Comment by OksanaN** [comment]
Белье, носки (мужчины)
1) Производитель/ТМ
2)Состав
3)Размер
4)Рост
5)Цвет

**Comment by OksanaN** [comment]
Товары для беременных и кормящих
1) Производитель/ТМ
2)Состав
3)Размер
4)Рост
5)Параметры:
ОГ
ОТ
ОБ
6)Количество

**Comment by OksanaN** [comment]
Спецодежда такие же свойства, как у одежды

**Comment by OksanaN** [comment]
Продукты питания
1)Производитель/ТМ
2)Состав
3)Вес с упаковкой
4)Вес без упаковки
5)Упаковка (коробка, жестяная банка. пищевая пленка...)
6)Срок годности
7)Вес

**Comment by OksanaN** [comment]
Кондитерские изделия такие же свойства, как и у продуктов

**Comment by OksanaN** [comment]
НАПИТКИ
1)Производитель/ТМ
2)Состав
3)Вес с упаковкой
4)Вес без упаковки
5)Объем (мл, литры)
6)Упаковка (коробка, жестяная банка. пищевая пленка...)
7)Срок годности
8)Вес

**Comment by tibrus** [comment]
Основная цель, это определение возможных типов полей. Замечу типов, а не названий.
Т.е. какое значение может содержать поле, например:
- размер - 42,43,44,45 (массив значений, значит тип поля будет список значений)
- вес - 30 кг. (обычное текстовой поле)
- длина - 30 см (обычное текстовой поле)
- цвет - красный, зеленый, синий (массив значений, значит тип поля будет список значений)
...
Тем самым мы заранее определим типы полей для товаров, и сделаем красивый и практичный выбор содержимого поля пользователем.

**Comment by OksanaN** [comment]
Не совсем поняла, уточню.
То есть у одежды поле РАЗМЕР, значит массив 36,40,42,44,46 и т.д?
Также у обуви - 38,39,40,41,42,43,44 и т.д?

По цвету даже не знаю. насколько реально перечислить все цвета. Есть такие цвета, как коралловый, антрацит... их порядка тысячи.
Или по цветам внести основные, а потом сделать груфу "Другой" для ручного ввода?

**Comment by OksanaN** [comment]
Может, тогда мне проще у себя где-то начертить и скинуть вам фото?
Только куда скинуть?

**Comment by OksanaN** [comment]
И еще вопрос. Можно ли будет эти массивы добавлять потом, в процессе работы сайта?
Так как к примеру, графа Торговая Марка, мы не сможешь сейчас многое учесть. А в процессе работы могли бы добавлять эти торговые марки.

**Comment by OksanaN** [comment]
Да и по другоим графам. вдруг что-то не учтем

**Comment by tibrus** [comment]
Оксана, Вы так и не поняли. Нас интересует тип поля, а не его значения...
Нам не нужны все торговые марки, нужно только понимание содержимого: массив значений, текстовое поле или т.п.
На сегодняшний день, по вышеперечисленным Вами вариантам, мы уже определились, что у нас есть:
- массив значений
- текстовое поле
И дальше перебираем возможные доп поля товара, что все учесть все типы, как например тип поля - ссылка, нужно не нужно и т.д.

**Comment by OksanaN** [comment]
не понимаю, что такое массив значений.
Я сделала в ворде таблицу, напишите куда скинуть ее,  чтоб вы посмотрели и скажете потом так или не так

**Comment by tibrus** [comment]
41, 42, 43, 44, 45... - массив
130 см - текстовое поле

ibtcom@gmail.com

**Comment by OksanaN** [comment]
отправила на почту

**Comment by OksanaN** [comment]
Ну что, правильно ли я сделала или опять не так?

**Comment by OksanaN** [comment]
Игорь, уточните, массив - это когда есть выбор из нескольких значений?
