### ISSUE TITLE
Статусы закупки (этапы)

### ISSUE THREAD

**Issue by tibrus** [exoohub/sp#15]
#### 1. Сбор заказов
`Статус заказа: "Новый заказ"`
* Пользователь имеет право редактирования и удаления заказа.

`Статус товара: "Отказано"` - (спам, пользователь в черном списке и т.п.)
* Пользователь не имеет право редактирования заказа, только удаление.

`Статус товара: "Нет в наличии"`
* Пользователь имеет право редактирования и удаления заказа.

#### 2. Счет (Получение счета от поставщика)
* Запрос организатору на создание выкупа 2 (Да/Нет)

`Статус заказа: "Счет"`
* Пользователь не имеет право редактирования и удаления заказа.

`Статус товара: "Нет в наличии"`
* Запрос пользователю на `Создание заказа` с товарами `Нет в наличии` на выкуп 2 (если существует) или `Отказ` от заказа.

`Статус товара: "Замена"`
* Пользователь имеет право редактирования товаров только с данным статусом. `Заменить` или `Удалить`

#### 3. Оплата
* Пользователь не имеет право редактирования и удаления заказа.

`Статус заказа: "Оплата"`
* Пользователю предоставляются реквизиты для оплаты.

`Статус заказа: "Оплачен"`

`Статус заказа: "Отказано"`

`Статус заказа: "Не оплачен"`
* Пользователь попадает в черный список.
* Пользователь не имеет право изменять, но имеет право удалять заказ.

#### 5. Разбор товара (организатором)
`Статус заказа: "Разбор товара"`
* Начисление доплаты за "Выдачу товара", системой пользователю, за единицу заказа. (Параметр "Администратора")
* Вывод наклеек по товару и пользователям (html to xls)
  * Никнейм пользователя
  * Организатор
  * Наименование закупки
  * Наименование товара
  * Сумма за "Выдачу товара"
  * Офис "Выдачи товара"
* Запрет изменения пользователем "Офиса выдачи товара"

`Статус товара: "Есть в наличии"`

 `Статус товара: "Нет в наличии"` - Не решено !!!

#### 6. Товар в офисе
`Статус заказа: "Товар выдан"`

(прим.: Если хранение товара более "2" недель, штраф "2р."/"день", (Параметры "Администратора"))

**Comment by SvetlanaAlabieva** [comment]
Статус заказа: "Сбор заказов"-
этот статус не нужен

**Comment by SvetlanaAlabieva** [comment]
1. Сбор заказов

Статус заказа: "Новый заказ"

Если существует выкуп 2, разрешить организатору изменять статус у заказа на "Новый заказ" Это в том случае, если после запроса счета у поставщика на наличие товара чего-то не будет в наличии и тогда организатор такому товару будет менять статус из "нет в наличии" на "новый заказ"? И все таки еще раз хочется уточнить если в одном заказе у одного пользователя есть 3 товара, 2 из которых есть у поставщика а третьего нет в наличии он сможет перенести один этот товар а не весь заказ в новый выкуп?

**Comment by SvetlanaAlabieva** [comment]
Статус товара: "Нет в наличии"

Пользователь имеет право редактирования и удаления заказа. Здесь организатор не может поставить статус товара нет в наличии. Он еще не делал запрос поставщику это по
лучается во второй этап -счет

**Comment by SvetlanaAlabieva** [comment]
На этапе "счет" еще всплывающее окно в котором организатора система будет спрашивать создать новый выкуп(выкуп 2) или закрыть закупку.

**Comment by OksanaN** [comment]
Пользователь попадает в черный список (точнее ему ставится черная метка) не на стадии СЧЕТ, а на сдадии ОПЛАТА.
То  есть, в  том случае ,если он не оплатил заказ на стадии ОПЛАТА, ему присваивается статус ОТКАЗАНО(НЕ ОПЛАЧЕНО) и ставится черная метка.

В случае, если ранее в какой-то закупке участник получил черную метку, то в данной закупке присваивается статус ОТКАЗАНО (но в черный черную метку он здесь не получает, т.к. он ее получил ранее)

**Comment by tibrus** [comment]
Изменения от 11.04
Этап 5 -  `Статус товара: "Нет в наличии"` - Не решено !!!

**Comment by SvetlanaAlabieva** [comment]
4. Ожидание товара (товар в пути)На этом этапе пусть будет браться с организаторов наш процент -2%. Т.е. как только организатор перевел закупку в статус ожидание товара, ему автоматически будет начисляться оплата за закупку. Далее на стадии разбор товара, если чего то не будет хватать из товаров (не доложил поставщик) при присвоении этому товару статуса "нет в наличии" этот товар не переносится в след. стадию -раздача.  а вот что с этим товаром дальше? Можно организатору сделать на выбор 2 варианта: 1) если он списался с участником и тот отказался ждать (просит вернуть деньги)-просто удалять такой товар, если он согласен чтобы в след. выкуп пришел его товар-тогда получится товар не сможет пройти все стадии (сбор минималки, оплату и т.д.) то организатор наверно вручную будет себе помечать такие товары а этот все таки придется просто оставлять со статусом -нет в наличии. Такие ситуации будут крайне редко и я не думаю что организатору они доставят сильное беспокойство в плане переписывания товаров вручную.

**Comment by OksanaN** [comment]
Удалять ничего нельзя! Мы ничего не удаляем, а присваеваем статусы!
Удалить может только участник закупки из своей корзины до стопа.
И тут, мне кажется, 2 варианта.
Присваивается статус "нет в наличии" и переносится в следующий выкуп.
И в новом выкупе уже участник либо удаляет его из своей корзины (и организатор возвращает ему деньги) - это первый вариант.
Второй вариант - в ручную менять статус "нет в наличии" на "новый заказ". И когда подойдет срок оплаты, организатор просто поменяет статус на "оплачено" и дальше всё как обычно.

Здесь только получается 2 нюанса:
1)без записей организатору не обойтись (где-то должен себе в блокноте помечать это и не забыть)
2)сумма ,с которой мы будем брать 2% будет задваиваться. Т.е. в первом выкупе организатор оплатит с этого заказа 2%, и в следующем выкупе опять с него заплатит 2%.


Еще пришла в голову мысль, не завершать закупку, пока товар из "нет в наличии" не перейдет также в офис. То есть, если поставщик не доложил товар и обязался выслать его со следующим выкупом, то организатор будет заходить в этот выкуп и именно этот, "зависший" товар переводить из "нет в наличии" в "офис".
Но тут опять проблема: из-за одного товара, который поставщик не доложил, будет "висеть" вся закупка. И через какое-то время мы можем получить большое колличество "зависших" закупок.

В общем, я думаю, оптимальный вариант, это переносить товары со статусом "нет в наличии" в следующий выкуп, а там участник из корзины должен будет его удалить (если он отказывается от него) либо удалить и заказать вновь (если он хочет дождаться его), для того, чтобы  этот товар прошел все стадии.

**Comment by OksanaN** [comment]
Игорь, может у вас что-то более умное назрело по этому поводу?)))

**Comment by tibrus** [comment]
Сорри пока не думали, срочно хотим админку закончить.
