### ISSUE TITLE
Регистрация на сайте 

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#17]
1) При регистрации на сайте и повторном входе на сайт в графе "имя пользователя" выдает адрес эл. почты (галочку запоминания пароля ставила)

**Comment by OksanaN** [comment]
У меня в первый раз тоже выдал адрес электронки.
Теперь выдает как надо, логин.

**Comment by tibrus** [comment]
Иногда будете наблюдать разные "глюки", значит там идет работа.
