### ISSUE TITLE
Транспортные расходы

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#18]
2)Как УЗ будет видеть долг по транспортным расходам? (отдельной графой в заказе или ему будут приходить оповещения?)

**Comment by tibrus** [comment]
Отдельной графой, суммируется с суммой оплаты заказа, смотрите в товарах заказа.
А зачем извещать покупателя, если он сразу получает общую сумму к оплате в т.ч. с доставкой.

**Comment by SvetlanaAlabieva** [comment]
да, если ОРГ указал сумму Транспортных расходов на стадии "Оплата", а если ОРГ будет указывать Транспортные расходы на стадии "разбор товара" то УЗ может не понять почему у него висит долг в 15-20 руб? Может лучше сделать отдельной графой с оповещением УЗ, что у него есть долг за Транспортные расходы?
