### ISSUE TITLE
Варианты названий этапов закупки

### ISSUE THREAD

**Issue by tibrus** [exoohub/sp#2]
#### Статус - Завершенная

**Comment by tibrus** [comment]
Этап 3 - Доставка

**Comment by SvetlanaAlabieva** [comment]
Этап 3 -давайте оставим ожидание товара, т.к если указать что это доставка, пользователи будут путаться.

**Comment by SvetlanaAlabieva** [comment]
По поводу 2 этапа-может лучше  назвать его Предоплата? Фактически так и есть, сначала пользователи оплачивают а уже потом получают заказ

**Comment by mufasaAG** [comment]
Тут опять таки возникает момент. Оплата это подразумевает 100%, а предоплата это часть суммы. Как я понимаю, организатор который первый раз проводит закупку не имеет права брать предоплату. Так что надо думать.

**Comment by SvetlanaAlabieva** [comment]
Почему он не имеет права брать 100 % предоплату? Он как раз имеет полное право на это, т.к. очень много недобросовестных пользователей, которые оставляют свой  заказ и не платят потом

**Comment by tibrus** [comment]
> По поводу 2 этапа-может лучше назвать его Предоплата?

Этап 2 - ~~Оплата~~ Предоплата

**Comment by OksanaN** [comment]
Совместные покупки всегда работают по предоплате. То есть сачала участники закупки переводят деньги на карту организатору закупки, а потом организатор на эти деньги выкупает товар у поставщика.
Но принято называть это ОПЛАТА
