### ISSUE TITLE
Статусы товаров

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#21]
5)Статусы заказов-возможность менять статусы вручную

**Comment by tibrus** [comment]
Зачем??? Вы сами говорили, статус можно изменить только на один шаг вперед. В чем тогда отличия от текущего функционала?

**Comment by SvetlanaAlabieva** [comment]
Если на стадии "разбор товара" поставщик не доложил товар как быть в такой ситуации? я должна оповестить пользователя о том, что его заказа нет в наличии

**Comment by tibrus** [comment]
Так это статус товара, а не заказа. Он в работе.
