### ISSUE TITLE
Сообщения на сайте 

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#23]
7)Не отправляются сообщения ОРГУ от пользователя и наоборот

**Comment by tibrus** [comment]
Может ли пользователь:
Удалить свои исходящие сообщения?
Удалить входящие сообщения адресованные пользователю?

**Comment by SvetlanaAlabieva** [comment]
да

**Comment by SvetlanaAlabieva** [comment]
протестировала, уведомления пришли, сообщения удаляются
