### ISSUE TITLE
Оповещения об оплате

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#25]
9)Оповещения УЗ об оплате (т.е. когда ОРГ присвоил статус оплата надо как то оповещать, может мигающим сообщением в ленту новостей либо по другому)

**Comment by OksanaN** [comment]
Я, как участник закупки, заказала в одной закупке часы, организатор провел закупку по всем этам, но мне не пришло никакое оповещение об оплате, ничего не оплачивала.
А в результате мой заказ оказался в офисе.....

**Comment by tibrus** [comment]
Не совсем понял, в какой ленте новостей? Зачем оповещать? Если в заказе у пользователя стоит отметка "Заказ оплачен"?
Обычно необходимо оповестить пользователя об его дальнейших действиях, а в данном случае это просто информация, которая в принципе указана в заказе.
И так как мы даем возможность оргу убирать отметку об оплате(на случай ошибки), то мы будем несколько раз отправлять сообщение пользователю об оплате, т.к. действие оповещения пользователю привязано к отметке об оплате.
