### ISSUE TITLE
Импорт каталога 

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#26]
10)Импорт в каталоге с помощью прайс листа поставщика либо с самого сайта поставщика

**Comment by OksanaN** [comment]
Да, по каталогам постащиков непонятно.
Как я ранее поняла, будут храниться каталоги с поставщиками со всеми товарами. А как все эти товары загрузить?

**Comment by tibrus** [comment]
##### Вроде есть решение
Для орга представляем информацию по категориям, а именно:

id | Название | - | - | -
------------ | -------------  | ------------- | ------------- | -------------
... | ... | ... | ...
33 | Мужчинам/Джинсы | Размер | Длина | Цвет
34 | Мужчинам/Рубашки | Размер | Цвет| 
35 | Мужчинам/Аксессуары |  |  |
... | ... | ... | ...

На основании этой таблицы орг формирует excel файл следующим образом:

Наименование | Цена | Фото | Категория | - | - | -
------------ | -------------  | ------------- | ------------- | ------------- | ------------- | -------------
Часы Orient  | 5500 | 1.jpg | 35 |  |
Джинсы Colins  | 6200 | 1.jpg | 33 | 38,40,42 | 130,140 | серые,белые
Рубашка Nike  | 2300 | 1.jpg | 34 | 38,40,42 | серая,белая

Т.к. свойства товаров в категориях хранятся по порядку(уникальный id), то и в excel свойства указывать по порядку, на основании указанной категории
