### ISSUE TITLE
Свободные поставщики 

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#27]
11)Возможность просмотра свободных поставщиков, прежде, чем выбрать из списка (т.е. новый ОРГ мог зайти сначала на сайт поставщика, ознакомиться с условиями и уже потом подавать на него заявку)

**Comment by tibrus** [comment]
При создании закупки, теперь можно открыть список поставщиков с ссылками, и перейти для ознакомления на сайт.
Вкладка открывается новая, диалоговое окно с выбором поставщика не закрывается и остается в прежнем состоянии для ожидания выбора..

**Comment by SvetlanaAlabieva** [comment]
протестировала, закупку отправила на модерацию из списка свободных поставщиков)
