### ISSUE TITLE
Разделы товаров

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#3]
Предлагаем 2 варианта категорий и под категорий и хотим с Вами посоветоваться как лучше сделать: 
### Женщинам: 
1.верхняя одежда и головные уборы 
2.одежда 
3.обувь 
4.сумки, галантерея 
5.белье и купальники 
6.украшения, аксессуары, бижутерия         
### Мужчинам: 
1.верхняя одежда и головные уборы 
2.одежда 
3.обувь 
4.белье         
### Детям: 
1)верхняя одежда и головные уборы
2)одежда
3)обувь
4)игрушки
5)товары для детей     
### Красота и здоровье 
1)косметика и парфюмерия 
2) здоровье, оптика       
### Продукты 
1)сладости 
2)напитки, чай,кофе 
3)продукты питания        
### Техника 
1)ПК, электроника 
2)бытовая техника       
### Дом и дача 
1)Мебель, интерьер, текстиль 
2)хозтовары, посуда, бытовая химия 
3)товары для животных 
4)все для сада и огорода 
5)строительство и ремонт      
### Авто и аксессуары 
1)все для авто 
2) инструменты        
### Отдых, развлечения, спорт: 
1)рукоделие и хобби 
2)все для спорта 
3) все для рыбалки 
3)товары для праздников, сувениры, подарки 
4)развлекательные мероприятия    
### Книги и канцтовары: 
1)книги 
2)канцтовары и офисные принадлежности       
### Пристрой организаторов

**Comment by OksanaN** [comment]
Второй вариант
1.ЖЕНЩИНЫ
-одежда
-верхняя одежда
-чулочно-носочные изделия, белье и купальники
-товары для беременных

2.МУЖЧИНЫ
-одежда
-верхняя одежда
-обувь
-белье. носки

3.ДЕТИ
-одежда 
-верхняя одежда
-обувь
-белье, носки, колготки
-игрушки
-товары для новорожденных
-детская косметика

4.КРАСОТА И ЗДОРОВЬЕ
-косметика и парфюмерия
-уход за телом и волосами
-оптика
-возможно, ортопедичечкая обувь и корректтирующее белье.

5.ДОМ И ДАЧА
-мебель, интерьер
-посуда и кухонные принадлежности
-хозтовары
-текстиль
-бытовая химия
-строительство и ремонт
-зоотовары и растеневодство

6.ОТДЫХ,РАЗВЛЕЧЕНИЯ,СПОРТ
-товары для зимнего спорта
-товары для летнего спорта
-баня и сауна
-товары для праздников
-баня и сауна
-туризм
-рыбалка и охота
-товары 18+
-товары для творчества и рукоделя
-коллекционирование
-экскурсии, билеты

7.КОЖГАЛАНТЕРЕЯ И ГАЛАНТЕРЕЯ
-сумки, кошельки, обложки для документов
-ремни, подтяжки
-часы
-зонты
-шапки. шарфы, перчатки
-бижутерия и аксессуары для волос
- галантерея для мужчин (галстуки, запонки)
-подарки и сувениры (куда их отнести???)

8.КНИГИ,КАНЦТОВАРЫ И ШКОЬНЫЕ ТОВАРЫ (нужно ли в отдельную категорию???)
-школьные товары
-товары для офиса
-товары для творчества
-открытки. плакаты, вывески
-письменные принадлежности
-детские книги
-литература для взрослых
-учебная литература

9.ТЕХНИКА,ЭЛЕКТРОНИКА, АВТОТОВАРЫ
-бытовая техника
-элементы питания
-аксессуары для пк, телефонов и т.д
-элеткроника
-аксессуары для авто
-уход за автомобилемя
-автокресла

10.ПРОДУКТЫ
-продукты
-напитки
-всё для суши
-чай. кофе
-сладости
(или вобще можно без подкатегорий)

11.ПРОЧЕЕ
-спецодежда
-(может сюда "засунуть" книги и канцтовары и не делать для них отдельной категории?)

12.ЗАРУБЕЖНЫЕ ЗАКУПКИ

13.ПРИСТРОЙ ОРГАНИЗАТОРОВ

**Comment by OksanaN** [comment]
И еще такой вопрос: подкатегорий лучше сделать больше, так сказать с учетом на будущее?
Или лучше сжато написать, меньше?

**Comment by SvetlanaAlabieva** [comment]
еще забыла категорию Прочее 1)спецодежда и пока больше ничего не могу отнести сюда. Также думаю что возможно категорию авто и аксессуары совместить с техникой и добавить туда еще под категории: 1)все для авто 2) инструменты 3)аудио, фото и видео техника 4) пк, электроника 5)бытовая техника. Товары для укладки волос мне кажется будет правильней добавить в категорию красота и здоровье либо добавить в категорию техника.

**Comment by tibrus** [comment]
> И еще такой вопрос: подкатегорий лучше сделать больше, так сказать с учетом на будущее?
> Или лучше сжато написать, меньше?

Администратор в своей панели управления, может изменять категории в любое время. Только Вы должны учитывать, если к категории уже привязали закупку, то категорию можно только переименовать или переместить, но не удалить.

Соответственно остальные, свободные категории, можно удалять и создавать.

А по поводу самих названий категорий, мы Вам точно не подскажем. Вам это в разы виднее.

**Comment by SvetlanaAlabieva** [comment]
Ну все таки на Ваш взгляд под категории стоит разбивать более подробно или лучше сделать более обобщенно?

**Comment by mufasaAG** [comment]
Если сделать обобщенно, то будет каша и фильтр будет огромен. Таким образом мы усложним работу с выбором. Если мы создадим больше категорий, то создадим более комфортный выбор и комфортную работы и при выборе и при заполнении.

**Comment by SvetlanaAlabieva** [comment]
Т.е. лучше разбить под категории как это сделано у Оксаны?

**Comment by SvetlanaAlabieva** [comment]
Или самих категорий сделать больше?

**Comment by mufasaAG** [comment]
Да лучше разбить под категории и рекомендую в категорию "Прочее" добавлять действительно то, что не попадает в общие категории. Ведь существуют привычные и общие категории, которые должны ими же и оставаться, не забирать их значимость.

**Comment by mufasaAG** [comment]
В итоге мы получим Обширный список категорий и не нагруженные под категориями. 
Проще: уменьшим категории, увеличим под категории, увеличим категории, уменьшим под категории.

**Comment by SvetlanaAlabieva** [comment]
Значит Вы советуете сделать больше под категорий и меньше категорий?

**Comment by mufasaAG** [comment]
Советую больше категорий, даже прапорционально

**Comment by SvetlanaAlabieva** [comment]
На счет привычных-на многих сайтах почему то в прочее относят пристрой организаторов хотя на мой взгляд лучше сделать это отдельной категорией т.к. не каждый догадается что пристрой находится в прочих

**Comment by SvetlanaAlabieva** [comment]
Ясно. В какие сроки необходимо предоставить точный список категорий и под категорий?

**Comment by mufasaAG** [comment]
Пристрой нужно обдумать куда его вынести. Пристрой это отдельная история)

**Comment by mufasaAG** [comment]
Конечно нужно чем быстрее тем лучше, но нужно хорошо обдумать, подкорректируем вместе

**Comment by SvetlanaAlabieva** [comment]
А что бы Вы сейчас подкорректировали или может быть вынесли отдельной категорией?

**Comment by SvetlanaAlabieva** [comment]
если начать с первой категории Женщины: головные уборы отдельной под категорией выносить? и еще можно добавить под категорию чулочно-носочный ассортимент

**Comment by mufasaAG** [comment]
Под категории Вы пишете все что считаете нужным и касаются только этой категории. Ну а под корректировать никогда не поздно

**Comment by SvetlanaAlabieva** [comment]
У нас такой вопрос: если в одной закупке есть товары, которые относятся к нескольким категориям и подкатегориям, соответственно, при создании закупки, мы выбираем несколько категорий. Как мы понимаем, в таком случае закупка будет отражаться в каждой категории. Не будет ли это затруднять работу сайта и не получится ли каши?

**Comment by mufasaAG** [comment]
Если создавать закупку с одним типов товаров и одного поставщика и не давать возможности в данную закупку добавлять другого поставщика с другим типом товара, то каши не должно быть. Пусть будет несколько закупок одного организатора, но закупки будут соответствовать группам товаров. Организатор создает закупку только с одним поставщиком.

**Comment by SvetlanaAlabieva** [comment]
У одного поставщика может быть представлены несколько типов товаров: пример: текстиль, одежда, обувь, аксессуары и т.д.  и как быть с такими поставщиками?

**Comment by mufasaAG** [comment]
Ничего страшного так как у нас один поставщик и каталог привязан к данному поставщику. Ведь у каждой группы товаров будет своя обложка, разбито по под категориям и т.д.

**Comment by SvetlanaAlabieva** [comment]
То есть, если у поставщика, к примеру, и одежда и обувь, то организатор будет создавать одну общую закупку, но одежда будет отражаться только в одежде, а обувь только в обуви???

**Comment by SvetlanaAlabieva** [comment]
например, есть такой поставщик https://www.sima-land.ru/
Как эта закупка будет отражаться в категориях?

**Comment by mufasaAG** [comment]
Изучив Вашу ссылку, понимаем, что могут возникнуть моменты, не удобные для оформления закупки. Сейчас рассматриваем и прорабатываем все варианты оформления закупки, дабы избежать путаницы и каши. Когда выберем оптимальный вариант, мы Вам его предоставим и полноценно ответим на Ваш вопрос.

**Comment by SvetlanaAlabieva** [comment]
Хорошо, спасибо

**Comment by SvetlanaAlabieva** [comment]
А если сделать так: к примеру поставщик сима ленд-открывается закупка, идет описание закупки и в конце делать ссылки на др. категории этого же поставщика, т.е. будет выглядеть так: описание закупки далее в конце  ссылки на др. категории этого же поставщика https://www.sima-land.ru/suveniry/ сувениры, https://www.sima-land.ru/igrushki/ игрушки и т.д. и уже кому надо будут проходить по этим ссылкам но уже в другую категорию

**Comment by SvetlanaAlabieva** [comment]
и тогда каждый товар будет находиться в своей категории

**Comment by SvetlanaAlabieva** [comment]
Женщинам:

1.одежда 
2.обувь 
4.сумки, галантерея 
5.белье 

Мужчинам:

1.одежда 
2.обувь 
3.сумки, галантерея
4.белье

Детям:

1.одежда
2.обувь
3.игрушки
4.товары для детей

Все для красоты и здоровья

1)косметика, парфюмерия 
2) здоровье

Продукты

1)продукты питания 
2)напитки 
3)кондитерские изделия


Техника

1)электроника 
2)бытовая техника
3)все для авто 

Товары для дома и дачи

1)Мебель, текстиль 
2)посуда  
3)хозтовары
4)товары для животных 
5)все для сада и огорода 
6)канцтовары


Отдых, спорт, развлечения

1)рукоделие, хобби 
2)все для спорта 
3) рыбалка, охота, туризм 
3)все для праздника 
4)досуг 

Прочее

**Comment by mufasaAG** [comment]
Предлагаю добавить в разделы:
 - Мужчинам
    - Одежда
    - Обувь
    - Аксессуары
 - Женщинам
    - Одежда
    - Обувь
    - Аксессуары
 - Детям
    - Одежда
    - Обувь
    - Игрушки

**Comment by SvetlanaAlabieva** [comment]
Мы выше написали разделы и подразделы. Если мы оставим как у Вас, тогда нам некуда будет отнести к примеру белье, сумки, товары для детей и т.д.
