### ISSUE TITLE
Дизайн сайта

### ISSUE THREAD

**Issue by OksanaN** [exoohub/sp#31]
Вопросы по дизайну сразу озвучивать или оставить на потом?

**Comment by tibrus** [comment]
Пока функционал, но если есть условия, можно начинать описывать.

**Comment by SvetlanaAlabieva** [comment]
Игорь, здесь ссылка на сайт, http://ru.wix.com/website-template/view/html/1610?originUrl=http%3A%2F%2Fru.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fonline-store%2F3&bookName=create-master-new&galleryDocIndex=1&category=online-store&metaSiteId=  возможно отсюда можно взять картинку лимона и еще понравились зеленые кнопки, которые также можно сделать на всех страницах. Фон можно оставить белым. Еще есть пожелания в размерах картинок, сделать их чуть меньше и в самих закупках и на главной (обложка закупок)

**Comment by SvetlanaAlabieva** [comment]
![image](https://cloud.githubusercontent.com/assets/11230912/10341080/dc50a6ee-6d1b-11e5-9a24-b5f286c3451c.png)
Игорь, очень нравится вот такой оттенок зеленого. Можно его поменять? Полноценное фото картинки скину в скайп

**Comment by SvetlanaAlabieva** [comment]
Игорь, по статусам товара можно сделать так:
новый заказ-зеленый цвет
счет-желтый
оплата-красный (можно не ярко выраженный цвет)
ожидание товара-серый
разбор товара-голубой (как у нас на сайте)
в офисе-оранжевый

**Comment by SvetlanaAlabieva** [comment]
Лимон, оставляем такой как сейчас, а надпись (название) зеленым цветом (оттенок как на фото выше). И еще можно попросить, если я нахожусь во вкладке к примеру мои заказы, ее выделять зеленым, если на главной -ее зеленым. Т.е. на какой странице в данный момент нахожусь-та и выделена цветом. Точно также как по категориям.

**Comment by SvetlanaAlabieva** [comment]
забыла про статус -отказано-темно-фиолетовым)
