### ISSUE TITLE
Профиль пользователя

### ISSUE THREAD

**Issue by tibrus** [exoohub/sp#32]
- [ ] Необходимо вставить отзывы (В работе)
- [ ] Подключить аватары (В работе)

**Comment by tibrus** [comment]
Готово.
- [ ] Необходимо вставить отзывы (В работе)
- [ ] Подключить аватары (В работе)

**Comment by SvetlanaAlabieva** [comment]
Здесь не поняла, нужно написать нужны галочки или нет?

**Comment by tibrus** [comment]
Для себя делаю пометки, что еще необходимо добавить в компонент

**Comment by SvetlanaAlabieva** [comment]
)))
