### ISSUE TITLE
Стадия "разбор товара" 

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#34]
на стадии разбор товара, при присвоении заказу статуса "нет в наличии", в случае начисления транспортных расходов, на этот заказ также начисляются транспортные расходы и еще можно попросить этот заказ как то выделять (другим цветом), чтобы в общем списке всех заказов по одной закупке его сразу было видно

- [x] начисляются транспортные расходы товарам со статусом "нет в наличии"
- [ ] выделять (другим цветом)

**Comment by tibrus** [comment]
- [ ] начисляются транспортные расходы товарам со статусом "нет в наличии"
- [ ] выделять (другим цветом)

**Comment by tibrus** [comment]
> заказ как то выделять (другим цветом), чтобы в общем списке всех заказов по одной закупке его сразу было видно

По сути, оргу лучше показать еще и список всех товаров в закупке, находящихся в статусе "Разбор товара", может тогда лучше создадим такую страницу?
