### ISSUE TITLE
Товары в заказе 

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#35]
в одном заказе есть 2 товара. один оплачен, другой нет. как быть? можно их как то разделить каждой строкой? или может быть 1 товара заказали 3шт к примеру, 2 оплатили а 1 товар  нет. Также в заказе нет итоговой суммы, если заказано 3 шт. товара, т.е. идет указание что заказано 3 шт, но общей суммы нет

- [x] итоговая сумма
- [x] пересчет итоговой суммы, при изменении статуса у товара "нет в наличии" (ОРГ)
- [x] пересчет итоговой суммы, при изменении статуса у товара "нет в наличии" (Заказ покупателя)

**Comment by tibrus** [comment]
Как это один оплачен, другой нет? Оплачивается заказ, в котором есть товары и расходы по доставке.
Если в заказе появились корректировки (товара нет в наличии), то изменяется общая сумма заказа.

**Comment by SvetlanaAlabieva** [comment]
Но ведь такая ситуация может быть, что пользователь 1 товар оплатит а второй нет и как тогда их разделять?

**Comment by tibrus** [comment]
Вообще это называется не оплаченный заказ, какая разница сколько товаров. Так можно сказать и за транспортные расходы, за один товар он оплатил тр. расходы, а за второй нет.
Есть заказ, есть сумма к оплате, она и подлежит оплате, а не оплачивать 30% заказа, потому что так захотел)))
Не вопрос, если уж так необходимо, можем ставить статус у товара, не оплачен или т.п., но это как то странно)

**Comment by SvetlanaAlabieva** [comment]
Я согласна, что для адекватных людей это странно)))), но в СП есть такие ситуации, когда пользователи очень безответственно относятся к своим заказам и были случаи что могут оплачивать частично свой заказ, объясняя это тем, что забыли удалить уже ненужный им товар

**Comment by tibrus** [comment]
Ок)) добавляем статус "не оплачен"?

**Comment by SvetlanaAlabieva** [comment]
да
