### ISSUE TITLE
Каталог товаров в закупке

### ISSUE THREAD

**Issue by tibrus** [exoohub/sp#4]
Когда организатор дублирует закупку в новую закупку, то копируется только каталог товаров и описание закупки.

При таком поведении, к концу года, база данных затрещит от количества одинаковых товаров.

### Есть предложение:
Привязать каталог товаров не к закупке, а к поставщику. Т.е. редактирование каталога остается в закупке, но хранение товаров и категорий будет привязано к поставщику.
#### Плюсы:
1. Снижение нагрузки на базу данных в 10-ки раз.
2. Если другой организатор в будущем берет данного поставщика, то каталог товаров будет уже заполнен.

#### Минусы:
Пока не нашли)))

**Comment by SvetlanaAlabieva** [comment]
Как будет выглядеть ситуация при изменении каталога товаров у поставщика? Организатор самостоятельно будет подгружать новые товары или это как то будет связано с поставщиком и они автоматически будут грузиться сами?

**Comment by mufasaAG** [comment]
Организатор самостоятельно дополняет базу данных новой продукцией поставщика. Но дополняет тогда когда в этом есть необходимость. К примеру организатор создает закупку по нижнему белью и по этим позициям работает. Поставщик добавляет новые позиции верхнего белья, и организатор решает работать по старым позициям или же добавить в закупку новую продукцию. И от этого уже идет заполнение. Зада стоит не тупо создать базу данных всей продукцией, а базу данных с рабочими позициями. Нужен продукт, добавили в базу данных, не нужен (то есть не торгует им никто) не добавляем в базу.

**Comment by SvetlanaAlabieva** [comment]
Если пользователи самостоятельно пройдя по ссылке на сайт поставщика увидят новый товар -они смогут в теме или на форуме к данной закупке оставить коммент или артикул или ссылку , чтобы организатор загрузил товар в каталог?

**Comment by mufasaAG** [comment]
Если организатор указал каталог поставщика, то конечно я как покупатель выбираю товар и если его нет в закупке, то списываюсь с организатором, а он потом добавляет в каталог

**Comment by SvetlanaAlabieva** [comment]
а переписка где будет на форуме или в личных сообщениях?

**Comment by tibrus** [comment]
Заказ товаров вне каталога организатора, будет осуществляться в специальной форме заказа. Данная форма скоро появится в ТЗ.

**Comment by OksanaN** [comment]
1 ВОПРОС: Удалять товары из базы данных поставщика (в случае, если поставщик сняд с продажи данный товар) можно будет? или он остается в базее навсегда.
2 ВОПРОС: Как будет выгдядеть база данных: это будет просто фото, либо фото+описание (арт, размер и т.д)+цена?

**Comment by tibrus** [comment]
> 1 ВОПРОС

Создавая отчет сегодня или через полгода, он будет формироваться заново, а не сохраняться в базе данных. В связи с этим, товар не удаляется, а имеет статус удален. Соответственно администратор может изменить этот статус, возможно и орг., тут нужно подумать.

По такому принципу работают все программы учета, в том числе и 1С. Т.к. если удалить товар, то по прошлым отчетам, он будет пустой строкой. 

> 2 ВОПРОС

Полностью все характеристики товара, чтобы не утруждать орга разбором не заполненных данных. Иногда проще с нуля сделать, чем искать соответствие.
