### ISSUE TITLE
Разбивка товара по количеству

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#43]
В заказе (при условии заказа пользователем товара одного наименования в кол-ве 2шт и более) разбить построчно товары (необходимо для того, чтобы на стадии "счет" и "разбор товара" можно было присвоить вручную статус "нет в наличии"

**Comment by tibrus** [comment]
Это что то совсем ужасное))) А как такое показывать покупателю? Тоже построчно)))

**Comment by SvetlanaAlabieva** [comment]
да))), иначе как он увидит что одного товара нет в наличии, а другой есть

**Comment by tibrus** [comment]
Я вас обрадую, ломать из за это придется почти 50% корзины, на это уйдет неделя. Я Вам говорил несколько раз, что товар с одинаковыми свойствами суммируется, почему сразу не сказали?

**Comment by SvetlanaAlabieva** [comment]
заказала я 2 КПБ одной расцветки и размера, а у поставщика на момент формирования счета в наличии только один. В заказе этот товар идет одной строкой, с указанием кол-ва 2шт, я не могу всему заказу присвоить статус "нет в наличии", т.к. тогда я потеряю весь заказ), поэтому будет очень удобно построчная разбивка товаров))))

**Comment by SvetlanaAlabieva** [comment]
да мне кажется мы уже обговаривали этот вопрос)

**Comment by SvetlanaAlabieva** [comment]
значит давайте отложим этот вопрос после открытия сайта, но желательно будет сделать это сразу после старта)))

**Comment by tibrus** [comment]
Мы это не обговаривали, я все фиксирую в заданиях, любой наш разговор. Ок сделаем позже

**Comment by tibrus** [comment]
Нельзя отложить на потом, слишком глобальный параметр. 
По сути атрибут "Количество" в данном случае вообще не приемлем. Как то все глупо получается.

**Comment by SvetlanaAlabieva** [comment]
Как Вы предлагаете сделать? оставить как сейчас?

**Comment by SvetlanaAlabieva** [comment]
Что за ситуация с оплатой?

**Comment by tibrus** [comment]
Записывайте наши разговоры пожалуйста. Позавчера обсуждали

**Comment by tibrus** [comment]
Я ничего не предлагаю, решайте сами. Сделаю как скажите

**Comment by SvetlanaAlabieva** [comment]
почему атрибут "кол-во " не приемлем?

**Comment by tibrus** [comment]
а как же мы тогда покажем покупателю, что 2-го товара нет в наличии
![image](https://cloud.githubusercontent.com/assets/6314709/10137951/b53c62f0-6604-11e5-99e7-a9d6fbc0dbd7.png)

**Comment by SvetlanaAlabieva** [comment]
если это конфеты, то там также будет минимальный заказ, к примеру фасовка по 300 гр., и если у поставщика нет в наличии определенного вида в кол-ве 300 гр, то ставим статус нет в наличии (еще на статусе счет). Тоже самое  с салфетками. Они идут в упаковках фасовкой по 100 шт, т.е пользователь заказывает 2 упаковки по 100 шт. Поставщик положил только 1 упаковку а вторую не доложил , и соответственно напротив 2-го заказанного товара ставим статус нет в наличии (на статусе разбор товара ) и возвращаем деньги за излишне уплаченную упаковку салфеток.
