### ISSUE TITLE
Ошибка при регистации

### ISSUE THREAD

**Issue by OksanaN** [exoohub/sp#44]
Игорь, при регистрации сайт выдает такую страницу
Invalid Parameter – yii\base\InvalidParamException

Unknown scenario: default

**Comment by OksanaN** [comment]
Разные буквы и символы в красном, синем и черном цвете.
Что это такое?
Уже раз 5 пыталась зарегистрирвоаться

**Comment by tibrus** [comment]
Я там сегодня работаю, включу позже.

**Comment by tibrus** [comment]
Работает. При загрузке проекта на сервер, необходимы тесты учетных записей и отправки e-mail

**Comment by SvetlanaAlabieva** [comment]
Необходимо создать новую почту? или можно со старым ником тестировать?

**Comment by tibrus** [comment]
> При загрузке проекта на сервер, необходимы тесты
