### ISSUE TITLE
Тестирование сайта

### ISSUE THREAD

**Issue by OksanaN** [exoohub/sp#47]
Игорь, уже второй или третий раз пытаюсь загрузить закупку для теста, заполняю несколько строк по товару (название, артикул, описание), выбираю категорию и всё у меня "соскакивает", страница обновляется и становится пусто. Делаю это снова - опять тоже самое. Итак до бесконечности.
Это связано с тем, что вы проводите на сайте работы или это какая-то ошибка?

**Comment by tibrus** [comment]
Только что проверял, добавил 3 товара, никаких проблем.
У вас проблемы с браузером, он сам обновляет страницу. Или найдите проблему или смените браузер.

**Comment by SvetlanaAlabieva** [comment]
у меня кстати тоже нормально грузятся все товары

**Comment by OksanaN** [comment]
Браузер у меня гугл хром, остальные сайты работают нормально.
Как я могу найти проблему?
