### ISSUE TITLE
Товары рядами, создание второго ряда

### ISSUE THREAD

**Issue by OksanaN** [exoohub/sp#48]
Игорь, добрый день!
Возникли некоторые сложности при заказе товаров рядами.
1. Детский костюм есть ряд рост104-1шт, рост110-1шт, рост116-1шт.
если заказали 104 -2шт, то по сути должен открыться второй ряд, но система его не открывает.
Если сложно сделать это в системе ,чтобы она автоматически открывала последующий ряд,может можно сделать так, чтобы хотя бы организатору какое-то оповещение приходило о том, что заказали размер из нового ряда и организатор должен в ручную создать этот ряд?

Без оповещения организатору очень сложно и гемморойно отслеживать, нужно ли создавать второй и последующие ряды.

А если они не создаются ни системой ни организатором, то весь смысл в рядах вобще теряется, так как пользователь не видит реальную картину, насколько собран тот или иной ряд (это первый нюанс по этому вопросу)
2. Второй нюанс - система предлагает выбрать ему место, СВОБОДНОЕ в ряду, а пользователю, возможно, нужен тот размер, который уже занят......

**Comment by tibrus** [comment]
1. В работе
2. И?

**Comment by OksanaN** [comment]
1 и 2  - это одно и тоже)
Просто объяснила, почему этло необходимо сделать.

**Comment by tibrus** [comment]
Ааааа, ок понял)))

**Comment by tibrus** [comment]
Добавляем автоматом или извещаем?

**Comment by SvetlanaAlabieva** [comment]
автоматом

**Comment by tibrus** [comment]
Детский костюм есть ряд 
рост 104 - 1шт,
рост 110 - 2шт,
рост 116 - 1шт.

Если мы автоматом плюсуем по одному, при первом выкупе, то во втором выкупе мы получим

рост 104 - 10шт,
рост 110 - 12шт,
рост 116 - 7шт.

Может тогда плюсуем не сохраняя в базу, т.е. когда товар показывается покупателю, и места "рост 104" в ряду уже заняты, то тогда, автоматом плюсуем для одно место?

**Comment by OksanaN** [comment]
Игорь, мы не поняли вобще, что вы имеете в виду.
Во-первых, ряды первого и второго выкупов никак не взаимосвязаны. При создании второго выкупа ряды обнуляются.

Если есть ряд 
рост 104-1шт
рост 110-2шт
рост 116-1шт

это в табличке выглядит так

104/110/110/116

если все размеры займут или закажут сразу 104 - 2шт, то это будет выглядеть так

104/110/110/116 (первый ряд)
104/110/110/116 (второйй ряд)

**Comment by tibrus** [comment]
Тогда говорите правильно.
ряды первого и второго выкупов никак не взаимосвязаны = ряды обнуляются!!!!!!!!!!!!!!

**Comment by tibrus** [comment]
как мне такое понять?

**Comment by tibrus** [comment]
я вам говорю о том, что новое место в ряду добавляется чисто визуально, не добавляясь в базу, что не "Обнулять ряды"

**Comment by tibrus** [comment]
Изменил. Протестируйте ряды.

**Comment by tibrus** [comment]
У рядов идет разбивка еще и по цвету, а возможно, что разбивка будет по длине, типу или т.п.?

**Comment by OksanaN** [comment]
Достаточно размера и цвета!

**Comment by tibrus** [comment]
В одном ряду может быть только один цвет?

**Comment by OksanaN** [comment]
Да!
