### ISSUE TITLE
Товары рядами. Создание двух разных рядов.

### ISSUE THREAD

**Issue by OksanaN** [exoohub/sp#49]
На примере тех же самых детских костюмов.
Артикул 12345 существует в красном цвете, в синим цвете и в зеленом цвете.
Каждый цвет идет рядами - рост 104,рост 110, рост 116.
Таким образом, мы получаем 3 разных ряда

красный
104-1шт,110-1шт, 116-1шт.

синий
104-1шт, 110-1шт,116-1шт.

зеленый
104-1шт, 110-1шт, 116-1шт.

Это разные ряды, абсолютно никак не связанные между собой. Можно собрать только красный ряд и если он собрался, то нет необходимости собирать синий и зелный.
Они существуют отдельно дркг от друга, просто идут у постащика под одни артикулом и под одной фотографией.

**Comment by tibrus** [comment]
Слышу впервые, поэтому на доработку в новых версиях.

**Comment by OksanaN** [comment]
Это просто получается как бы двойной ряд.

**Comment by tibrus** [comment]
Такое возможно?
красный
104-1шт,110-1шт, 116-1шт.

синий
104-1шт, 110-1шт

**Comment by SvetlanaAlabieva** [comment]
нет невозможно
