### ISSUE TITLE
Карточка Заказа

### ISSUE THREAD

**Issue by mufasaAG** [exoohub/sp#5]
- [x] Добавить в таблицу Заказа столбцы "стоимость доставки" и "итоговую цену".
- [x] Создать кнопки "Tab" для разделение информации и добавления нового функционала. 
- [x] Создать личную переписку в данной карточке, организатора с покупателем.
- [x] Указать статус пользователя
- [x] Убрать фото товара

http://sp.exoohub.com/sp/organizer/orders/view?id=2217#

**Comment by SvetlanaAlabieva** [comment]
Здесь не совсем поняла это так будет выглядеть карточка заказа товара?

**Comment by mufasaAG** [comment]
Это задание для разработчков
