### ISSUE TITLE
Невозможность восстановить пароль

### ISSUE THREAD

**Issue by OksanaN** [exoohub/sp#52]
Игорь, пароль к сайту невозможно установить потому, что сайт не залит на сервер? 
или это недоработка? Или что-то от нас требуется для этого?

**Comment by SvetlanaAlabieva** [comment]
Игорь, оповещение на почту сразу должно приходить?

**Comment by tibrus** [comment]
О чем?

**Comment by SvetlanaAlabieva** [comment]
о восстановлении пароля?

**Comment by tibrus** [comment]
да, но работать бедут только на сервере, кстати надо будет не забыть проверить

**Comment by SvetlanaAlabieva** [comment]
ясно)))) хорошо, запишу себе
