### ISSUE TITLE
Вывод списка офисов для пользователя

### ISSUE THREAD

**Issue by tibrus** [exoohub/sp#54]
В модальное окно при оформлении заказа и в профиле

**Comment by SvetlanaAlabieva** [comment]
а можно еще попросить сделать возможность добавления нескольких офисов. К примеру на данный момент у нас в Саратове 4 офиса а в дальнейшем будет 7. Чтобы мы могли самостоятельно добавить нужное количество офисов с возможностью отображения и добавления фото.

**Comment by tibrus** [comment]
А в чем проблема? добавляйте, в админке "Офисы"

**Comment by tibrus** [comment]
![image](https://cloud.githubusercontent.com/assets/6314709/10309051/e75ef470-6c42-11e5-9771-626a6961e254.png)


![image](https://cloud.githubusercontent.com/assets/6314709/10309477/7af4dd38-6c45-11e5-9055-e1a17b82d4f2.png)


![image](https://cloud.githubusercontent.com/assets/6314709/10309512/ad83d268-6c45-11e5-9095-713be568f44e.png)
