### ISSUE TITLE
Вопрос по второму (последующему) выкупу.

### ISSUE THREAD

**Issue by OksanaN** [exoohub/sp#56]
В первом выкупе был размерный ряд: рост 104-1шт, рост 110-1шт, рост 116-1шт.
Пользователи заказали 104 и 110 (116 никто не заказал). Я всё равно провела закупку (предположим, выкупила на свои средства). Создала второй выкуп. И во втором выкупе у меня получилось так, что 104 и 110 в ряду занято, а 116 свободно. То есть вся информация с первого выкупа перенеслась во второй выкуп. По сути, если заказы обнулились, то и ряды долджны обнулится, стать свободными. Или это как-то вручную надо имправлять?

**Comment by tibrus** [comment]
Понял, посмотрю. Скорее всего необходимо ряды привязывать к выкупу.

**Comment by tibrus** [comment]
В какой момент обнулять ряды?

**Comment by OksanaN** [comment]
Сразу, в момент создания нового выкупа.

**Comment by SvetlanaAlabieva** [comment]
Как только всплывает информационное окно об открытии нового выкупа

**Comment by tibrus** [comment]
Нужен тест
