### ISSUE TITLE
Ошибка с наклейками (штрихкодами)

### ISSUE THREAD

**Issue by OksanaN** [exoohub/sp#58]
Игорь, у меня какая-то ошибка с наклейками, путаница.
1. Названием закупки стоит моё - Яркая детская одежда, а товар - обезьянка (закупка Светланы).
2. После третьего выкупа наклейки мне "вышли" все кучей - сначала первого выкупа, потом второго, потом третьего, - всего на 2 листах. 
Думаю ,что правильнее будет, если наклейки будут "выходить" только того выкупа, который в данный момент я провожу.

**Comment by tibrus** [comment]
1. Исправлено
2. Исключено, т.к. показывает с жестким условием, только те товары, которые в статусе "Разбор товара"
