### ISSUE TITLE
Черная метка (неоплата заказа)

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#59]
Если проходит первый выкуп и в нем, 1 и более заказа не оплатили, организатор присваивает статус не оплачен и этот пользователь получает черную метку а заказ автоматически попадает в архив и более нигде не фигурирует.

**Comment by tibrus** [comment]
В заказе возможен просто отказ без черной метки?

**Comment by SvetlanaAlabieva** [comment]
возможен

**Comment by tibrus** [comment]
Где и кому показывать черный список пользователей?

**Comment by SvetlanaAlabieva** [comment]
черный список показывать  администраторам, организаторам в новых заказах. Т.е. если пользователь сделал заказ и у него стоит черная метка, то организатор увидит это в заказах.

**Comment by tibrus** [comment]
![image](https://cloud.githubusercontent.com/assets/6314709/10290676/2c3dda9c-6bae-11e5-9464-7a300000fc14.png)

**Comment by SvetlanaAlabieva** [comment]
отлично!!!
