### ISSUE TITLE
Условие "Предоплата"

### ISSUE THREAD

**Issue by mufasaAG** [exoohub/sp#6]
Нужно решить, в условиях закупки будет ли условие "Предоплата", то есть оплата во время сбора заказов, или нет?

**Comment by SvetlanaAlabieva** [comment]
Я считаю что лучше сделать предоплату уже после того, как набрана минималка, организатор меняет статус "сбор заказов" на статус "предоплата" и уже здесь все пользователи начинают оплачивать заказы. А еще лучше будет сделать когда между статусом "сбор заказов" и статусом "предоплата" будет промежуточный статус "счет" либо "ждем счет" ( это необходимо для уточнения наличия товара на складе поставщика) и уже когда поставщик подтвердит фактическое наличие товара, тогда те заказы которые есть у поставщика переводить в статус "предоплаты" а те, которых на данный момент нет на складе -присвоить статус новый заказ. Т.Е. эти заказы автоматически попадают на новый выкуп.
