### ISSUE TITLE
Менеджер: права и доступы 

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#60]
1) ID участника закупки может видеть только менеджер и сам пользователь у себя в профиле
2) при сканировании товара в офисе менеджеру выводить данные по заказу : наименование товара, кол-во, ник пользователя, ник ОРга, наименование закупки и после этого, менеджер подтверждает выдачу товара пользователю

**Comment by tibrus** [comment]
1. Скольки значный нужен ID участника?
2. Т.е. подтверждает нажатием к примеру "Enter"?

**Comment by SvetlanaAlabieva** [comment]
1)6-7 значный номер участника 
2)при сканировании товара в офисе менеджеру выводить данные на компьютере: покупатель-ник на сайте, офис, артикул товара, наименование товара, св-ва товара, цена СП, кол-во товара, сумма доставки.  Далее менеджер нажимает ентер и статус товара меняется на-товар в офисе.

**Comment by SvetlanaAlabieva** [comment]
Далее сканером товар выдаем пользователю и заказу присваивается статус выдан
