### ISSUE TITLE
При открытии нового выкупа 

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#62]
![image](https://cloud.githubusercontent.com/assets/11230912/10268282/d9da407c-6ac4-11e5-995c-ed9fc86dd0fa.png)
Игорь, можно переименовать "отправляется в архив" на "свободные поставщики"

**Comment by tibrus** [comment]
Как это закупку в "свободные поставщики"?

**Comment by SvetlanaAlabieva** [comment]
ее потом можно будет выбрать из списка свободных поставщиков???

**Comment by tibrus** [comment]
Светлана, речь идет о закупке, а не о поставщике. О нем идет речь в следующем диалоговом окне, при отказе, вспоминайте)))

**Comment by SvetlanaAlabieva** [comment]
да, правильно)))) тогда все норм)))
