### ISSUE TITLE
Указание цены в руб

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#63]
Игорь, чтобы не забыли, исправить прямоугольник, который показывается вместо руб. рядом с ценой

**Comment by tibrus** [comment]
Готово

**Comment by tibrus** [comment]
Светлана, когда смотрел через тимку, проскочил квадрат, посмотрите где именно?

**Comment by SvetlanaAlabieva** [comment]
хорошо

**Comment by tibrus** [comment]
Не забудьте)))

**Comment by tibrus** [comment]
Нужен квадратик)))

**Comment by SvetlanaAlabieva** [comment]
Игорь, вчера просматривала в ходе закупки пока не нашла где, сегодня буду еще внимательно смотреть)
