### ISSUE TITLE
Новая закупка 

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#66]
При одобрении новой закупки, возможность видеть закупку в общем каталоге на первой позиции. +1

**Comment by tibrus** [comment]
Между одобрением и активацией может пройти неделя, например орг набивал товары. Поэтому предлагаю поднять на первую позицию, когда орг активирует закупку.

**Comment by SvetlanaAlabieva** [comment]
хорошо, давайте так сделаем

**Comment by tibrus** [comment]
готово тестируйте
