### ISSUE TITLE
Штрих-коды и Сканер.

### ISSUE THREAD

**Issue by OksanaN** [exoohub/sp#71]
Игорь, если у нас штрих-код будет сканироваться 2 раза: первый - при поступлении заказов в офис, второй - при выдаче заказов.
Тогда, может, есть возможность, чтобы штрих-коды всё-таки выводились на заказы,а не на товары? Ведь наличие или отсутствие какого-либо заказа организатор проведет в системе, а штрих-коды нам нужны чисто для фиксации выдачи заказов.

**Comment by tibrus** [comment]
Да вы что издеваетесь......................
Я уже всю структуру сделал!!!!!!!!!!!!!!!

**Comment by OksanaN** [comment]
Нет, ни в коем случае! Просто спросила, возможно ли такое. Пусть будет как есть!
