### ISSUE TITLE
Запрос на открытие Следующего выкупа

### ISSUE THREAD

**Issue by OksanaN** [exoohub/sp#72]
Игорь, в ходе проведения закупки не всплыыает вопрос о том открыть ли следующий выкуп или отправить закупку в архив!

**Comment by tibrus** [comment]
При тестах не наблюдаю. 
При наступлении момента, опишите закупку, заказ и все остальное и не трогайте далее закупку.

**Comment by tibrus** [comment]
Ошибка актуальна?

**Comment by SvetlanaAlabieva** [comment]
Сейчас вроде нормально, сегодня еще раз проверим)
