### ISSUE TITLE
Админка

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#81]
Возможность списания (взаиморасчетов) долгов с организаторов вручную, путем введения определенной суммы.

**Comment by tibrus** [comment]
Что значит списания вручную?

**Comment by SvetlanaAlabieva** [comment]
к примеру отчетный период будет в конце текущего месяца 25 числа. Организаторы отчитались за текущий месяц, но за 5 дней (до конца тек. месяца) у них уже прошла еще одна закупка, и соответственно начисление за закупку, это пойдет в след. месяц на оплату. Они принесли по факту сумму и мы списали ее, а остальной долг уйдет на след. месяц

**Comment by tibrus** [comment]
![image](https://cloud.githubusercontent.com/assets/6314709/10461972/ac8d8b20-71e4-11e5-91eb-c7e4b8cb201d.png)
Выберите тип документа и зачисляйте)))
