### ISSUE TITLE
Организатор удалил товар в своей закупке

### ISSUE THREAD

**Issue by OksanaN** [exoohub/sp#82]
Игорь, такая ситуация: пользователь заказал товар, оформил в мои заказы.
А организатор взял и в организаторской удалил этот товар из закупки (например, он просто что-то перепутал, загрузил не тот товар, а потом спохватился и удалил его или даже нечаянно удалил).
Фактически получается, что этого товара нет, но у пользователя этот товар остается в заказе и проходит все стадии закупки, в том числе и оплачивать пользователь его должен и штрихкод на него выходит.
Как быть и что делать?

**Comment by tibrus** [comment]
Орг делает отказ в заказе.

**Comment by OksanaN** [comment]
Хорошо (нужно нам памятку для оргов сделать).
Игорь, а еще такой вопрос, помните еще давно (по-моему в Торнадо) я спрашивала можно ли будет оргу отменить дейтсвие? То есть поторопился или что-то не так сделал и чтобы он мог отменить это действие. Вы говорили тогда, что можно, но всего лишь на 1 шаг назад.
Так сейчас это можно или нет?
Вот, к примеру, я перевожу закупку на другую стадию, вспывает окно "Создать новый выкуп?" я автоматически нажимаю "Да". а сама хотела отказаться от закупки. Могу ли я вернуться на шаг назад?

**Comment by tibrus** [comment]
Нет, т.к. это вызовет очень большое количество изменений в базе данных. Мы это уже обсуждали со Светланой.
В данном случае за оргом ответственность в решении, равнозначно как удаление, при котором пути назад нет. Поэтому система предварительно и спрашивает в диалоговом окне о действии.

А решение по шагу +-1 было предварительным, т.к. небыло ТЗ и мы обсуждали варианты работы.
