### ISSUE TITLE
Категории и подкатегории на сайте 

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#84]
![image](https://cloud.githubusercontent.com/assets/11230912/10588920/40d14954-76b1-11e5-8e8e-61362a4ed5cc.png)
это в админке а вот так на главной 
![image](https://cloud.githubusercontent.com/assets/11230912/10588960/6f3e665a-76b1-11e5-8249-e938f151db07.png)
Игорь, необходимо сделать порядок как в админке.

**Comment by tibrus** [comment]
Исправлено
