### ISSUE TITLE
Раздел "Пристрой" 

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#9]

**Comment by SvetlanaAlabieva** [comment]
Пристрой -это товары, находящиеся у организатора в наличии. Товары могут быть абсолютно из разных категорий ( юбки, посуда, текстиль, канцтовары и т.д.). Эти товары накапливаются со временем, т.к. организатору периодически приходится выкупать товары, для того, чтобы состоялся выкуп. Если к примеру закупка идет рядами, то возможен такой вариант, что 80 % -это заказы пользователей, а остальные 20% выкуп организатора.  Пристрой может быть полноценной закупкой, которая проходит все стадии , также как и обычная закупка. Просто происходит это намного быстрей. На сбор может отводиться 2-3 дня, далее орг. переводит в оплату, потом разбор товара и доставка в офис. Поэтому в такой закупке могут быть абсолютно все разделы. Как лучше сделать: вынести пристрой отдельным разделом либо как вариант отфильтровать как зарубежные закупки?

**Comment by OksanaN** [comment]
Хочу добавить, что Пристрой разделяется по организаторам: пристрой Маши, пристрой Даши и т.д.
