### ISSUE TITLE
Статусы закупок (версия 1.08) СРОЧНО 

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#97]
Почему при одобрении закупки через раз или спонтанно стоит статус -не активна???

**Comment by tibrus** [comment]
После одобрения закупки, ей присваивается статус `Одобрено`, это временный статус, для извещения организатора.
После этого, как только орг изменяет закупку, ей присваивается статус `Не активна`, чтобы организатор понимал, что товары не отображаются, как и сама закупка, и ее необходимо активировать.

**Comment by SvetlanaAlabieva** [comment]
работает)
