### ISSUE TITLE
Закупки на главной (версия 1.08)

### ISSUE THREAD

**Issue by SvetlanaAlabieva** [exoohub/sp#98]
![image](https://cloud.githubusercontent.com/assets/11230912/10647488/56b6b38a-7841-11e5-8b81-f19674188988.png)
![image](https://cloud.githubusercontent.com/assets/11230912/10647500/6768aeae-7841-11e5-9ef5-9fa429129891.png)

Игорь, просьба сделать на главной (каталог) закупки и фотографии (товары) поменьше размером

**Comment by OksanaN** [comment]
И поместить на страницу не 20 фотографий с товарами ,как сейчас, а 60
